global:
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: demo

receivers:
  - name: demo
    slack_configs:
      - channel: prometheus-demo
        text: "{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}"
        send_resolved: true

